#include "media.h"
static struct spinlock media_lock;
static struct zeroos_media_track tracks[ZEROOS_MEDIA_MAX_TRACKS];
static struct zeroos_media_playlist playlists[ZEROOS_MEDIA_MAX_PLAYLISTS];
int media_system_init(void){spinlock_init(&media_lock);for(uint32_t i=0;i<ZEROOS_MEDIA_MAX_TRACKS;++i){tracks[i].used=0;tracks[i].gen=0;spinlock_init(&tracks[i].lock);}for(uint32_t i=0;i<ZEROOS_MEDIA_MAX_PLAYLISTS;++i){playlists[i].used=0;playlists[i].gen=0;spinlock_init(&playlists[i].lock);}return 0;}
int media_track_add(const char *title,const char *artist,uint64_t duration,uint64_t *id_out){if(!title||!artist||!id_out)return -1;uint64_t f=spin_lock_irqsave(&media_lock);for(uint32_t i=0;i<ZEROOS_MEDIA_MAX_TRACKS;++i){if(tracks[i].used)continue;if(tracks[i].gen==0xffffffffU)continue;tracks[i].gen++;if(tracks[i].gen==0)continue;tracks[i].used=1;tracks[i].duration_ms=duration;tracks[i].sample_rate=44100;uint32_t n=0;while(n<63&&title[n]){tracks[i].title[n]=title[n];n++;}tracks[i].title[n]=0;n=0;while(n<63&&artist[n]){tracks[i].artist[n]=artist[n];n++;}tracks[i].artist[n]=0;tracks[i].id=((uint64_t)tracks[i].gen<<16)|(i+1);*id_out=tracks[i].id;spin_unlock_irqrestore(&media_lock,f);return 0;}spin_unlock_irqrestore(&media_lock,f);return -1;}
int media_playlist_create(const char *name,uint64_t *id_out){if(!name||!id_out)return -1;uint64_t f=spin_lock_irqsave(&media_lock);for(uint32_t i=0;i<ZEROOS_MEDIA_MAX_PLAYLISTS;++i){if(playlists[i].used)continue;if(playlists[i].gen==0xffffffffU)continue;playlists[i].gen++;if(playlists[i].gen==0)continue;playlists[i].used=1;playlists[i].count=0;uint32_t n=0;while(n<63&&name[n]){playlists[i].name[n]=name[n];n++;}playlists[i].name[n]=0;playlists[i].id=((uint64_t)playlists[i].gen<<16)|(i+1);*id_out=playlists[i].id;spin_unlock_irqrestore(&media_lock,f);return 0;}spin_unlock_irqrestore(&media_lock,f);return -1;}
int media_playlist_add_track(uint64_t pid,uint64_t tid){uint64_t f=spin_lock_irqsave(&media_lock);uint32_t slot=(uint32_t)(pid&0xffffULL);uint32_t gen=(uint32_t)(pid>>16);if(slot==0||slot>ZEROOS_MEDIA_MAX_PLAYLISTS||gen==0){spin_unlock_irqrestore(&media_lock,f);return -1;}struct zeroos_media_playlist *p=&playlists[slot-1];if(!p->used||p->gen!=gen){spin_unlock_irqrestore(&media_lock,f);return -1;}uint64_t pf=spin_lock_irqsave(&p->lock);if(p->count>=ZEROOS_MEDIA_MAX_TRACKS){spin_unlock_irqrestore(&p->lock,pf);spin_unlock_irqrestore(&media_lock,f);return -1;}p->track_ids[p->count++]=tid;spin_unlock_irqrestore(&p->lock,pf);spin_unlock_irqrestore(&media_lock,f);return 0;}
int media_debug_validate(void){return 0;}
