#include "net_transport.h"
#define TCP_FIN 0x01
#define TCP_SYN 0x02
#define TCP_RST 0x04
#define TCP_ACK 0x10
static uint16_t rd16(const uint8_t*p){return(uint16_t)(((uint16_t)p[0]<<8)|p[1]);}
int net_udp_parse(const uint8_t*p,uint32_t n,struct net_udp_view*o){if(!p||!o||n<8)return -1;uint16_t len=rd16(p+4);if(len<8||len>n)return -1;o->source_port=rd16(p);o->destination_port=rd16(p+2);o->length=len;o->payload=p+8;o->payload_length=(uint16_t)(len-8);return 0;}
int net_tcp_input(struct net_tcp_conn*c,uint8_t f,uint32_t seq,uint32_t ack,uint32_t now,uint32_t timeout){if(!c)return -1;if(f&TCP_RST){c->state=TCP_CLOSED;return 0;}switch(c->state){case TCP_LISTEN:if(f&TCP_SYN){c->rcv_nxt=seq+1;c->snd_nxt++;c->state=TCP_SYN_RECEIVED;c->deadline=now+timeout;c->retries=0;return 1;}break;case TCP_SYN_SENT:if((f&(TCP_SYN|TCP_ACK))==(TCP_SYN|TCP_ACK)&&ack==c->snd_nxt){c->rcv_nxt=seq+1;c->snd_una=ack;c->state=TCP_ESTABLISHED;return 1;}break;case TCP_SYN_RECEIVED:if((f&TCP_ACK)&&ack==c->snd_nxt&&seq==c->rcv_nxt){c->state=TCP_ESTABLISHED;return 1;}break;case TCP_ESTABLISHED:if(seq!=c->rcv_nxt)return -2;if(f&TCP_FIN){c->rcv_nxt++;c->state=TCP_CLOSE_WAIT;return 1;}return 0;case TCP_FIN_WAIT_1:if((f&TCP_ACK)&&ack==c->snd_nxt)c->state=(f&TCP_FIN)?TCP_TIME_WAIT:TCP_FIN_WAIT_2;if(f&TCP_FIN){c->rcv_nxt++;c->state=TCP_TIME_WAIT;}return 1;case TCP_FIN_WAIT_2:if(f&TCP_FIN){c->rcv_nxt++;c->state=TCP_TIME_WAIT;return 1;}break;case TCP_CLOSE_WAIT:break;case TCP_CLOSING:if((f&TCP_ACK)&&ack==c->snd_nxt)c->state=TCP_TIME_WAIT;return 1;case TCP_LAST_ACK:if((f&TCP_ACK)&&ack==c->snd_nxt)c->state=TCP_CLOSED;return 1;case TCP_TIME_WAIT:break;case TCP_CLOSED:default:break;}return -1;}
int net_tcp_timeout(struct net_tcp_conn*c,uint32_t now,uint32_t limit,uint32_t interval){if(!c||!interval)return -1;if(c->state==TCP_CLOSED||c->state==TCP_ESTABLISHED||c->state==TCP_LISTEN||c->state==TCP_TIME_WAIT)return 0;if((int32_t)(now-c->deadline)<0)return 0;if(c->retries>=limit){c->state=TCP_CLOSED;return -1;}c->retries++;c->deadline=now+interval;return 1;}
